DROP TABLE contratto IF EXISTS;

CREATE TABLE contratto (
  id INT PRIMARY KEY AUTO_INCREMENT,
  id_tipo_contratto INT,
  id_tipo_livello INT,
  id_tipo_azienda INT,
  id_contratto_nazionale INT,
  attivo BOOLEAN,
  sede_assunzione VARCHAR(255),
  qualifica VARCHAR(255),
  data_assunzione DATE,
  data_inizio_prova DATE,
  data_fine_prova DATE,
  data_fine_rapporto DATE,
  mesi_durata INT,
  livello_attuale VARCHAR(255),
  livello_finale VARCHAR(255),
  dimissioni BOOLEAN,
  part_time BOOLEAN,
  part_timeA BOOLEAN,
  retribuzione_mensile_lorda VARCHAR(255),
  superminimo_mensile VARCHAR(255),
  ral_annua VARCHAR(255),
  superminimo_ral VARCHAR(255),
  diaria_mese VARCHAR(255),
  diaria_gg VARCHAR(255),
  ticket VARCHAR(255),
  valore_ticket VARCHAR(255),
  categoria_protetta BOOLEAN,
  tutor VARCHAR(255),
  pfi VARCHAR(255),
  assicurazione_obbligatoria VARCHAR(255),
  corso_sicurezza DATE,
  motivazione_fine_rapporto VARCHAR(255),
  pc BOOLEAN,
  scatti_anzianita VARCHAR(255),
  tariffa_partita_iva VARCHAR(255),
  canale_reclutamento VARCHAR(255),
  FOREIGN KEY (id_tipo_contratto) REFERENCES tipo_contratto(id),
  FOREIGN KEY (id_tipo_livello) REFERENCES livello_contratto(id),
  FOREIGN KEY (id_tipo_azienda) REFERENCES tipo_azienda(id),
  FOREIGN KEY (id_contratto_nazionale) REFERENCES contratto_nazionale(id)
);
